"""
plot_from_csv.py

This script reads SEIR simulation statistics from 'simulation_stats.csv'
(generated by SEIRABMCuda) and plots the Susceptible, Exposed, Infectious,
and Recovered populations over time.

Usage:
1. Ensure 'simulation_stats.csv' is in the same directory.
2. Run: `python3 plot_from_csv.py`

Dependencies:
- pandas: `pip install pandas`
- matplotlib: `pip install matplotlib`

Output:
- `seir_simulation_plot.png` (a line plot of SEIR populations).
"""

import pandas as pd
import matplotlib.pyplot as plt

def plot_seir_simulation(csv_filepath='simulation_stats.csv', save_path='seir_simulation_plot.png'):
    """
    Reads SEIR simulation data from a CSV file and plots the results.

    Args:
        csv_filepath (str): The path to the input CSV file.
        save_path (str): The path to save the generated plot image.
    """
    try:
        # Read the data from the CSV file
        df = pd.read_csv(csv_filepath)

        # Create a new figure and axis for the plot
        plt.figure(figsize=(12, 8))
        
        # Plot each of the SEIR states over time
        plt.plot(df['Time'], df['Susceptible'], label='Susceptible', color='blue')
        plt.plot(df['Time'], df['Exposed'], label='Exposed', color='orange')
        plt.plot(df['Time'], df['Infectious'], label='Infectious', color='red')
        plt.plot(df['Time'], df['Recovered'], label='Recovered', color='green')

        # Add title and labels for clarity
        plt.title('SEIR Model Simulation Results')
        plt.xlabel('Time (Days)')
        plt.ylabel('Number of Agents')
        
        # Add a legend to identify the lines
        plt.legend()
        
        # Add a grid for better readability
        plt.grid(True)

        # Save the plot to the specified file
        plt.savefig(save_path)
        print(f"Plot saved to {save_path}")

    except FileNotFoundError:
        print(f"Error: The file '{csv_filepath}' was not found.")
        print("Please make sure the simulation has been run and the CSV file exists.")

if __name__ == '__main__':
    plot_seir_simulation()
